# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-02 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcacione',
            name='estado',
            field=models.CharField(blank=True, choices=[('0', 'Entrada'), ('1', 'Salida')], max_length=40, null=True),
        ),
    ]
