# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-03 20:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20170802_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='JefeSupermercado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(blank=True, max_length=50, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='perfile',
            old_name='telefono',
            new_name='telefono_id',
        ),
        migrations.RemoveField(
            model_name='perfile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='perfile',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='perfile',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='perfile',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='perfile',
            name='pais',
        ),
        migrations.AddField(
            model_name='perfile',
            name='jefe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.JefeSupermercado'),
        ),
    ]
