# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-08 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_perfile_legajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcacione',
            name='device_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='marcacione',
            name='fecha',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marcacione',
            name='hora',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marcacione',
            name='observaciones',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
