# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-22 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170808_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcacione',
            name='zona',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
