# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-01 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_usuario_esta_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcacione',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marcacione',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
