# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-01 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20171101_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcacione',
            name='fecha',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marcacione',
            name='hora',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
